#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;
BEGIN {
    unshift @INC, "/home/kat/files/git/public/perl/Mojolicious-Plugin-Foil/lib";
    unshift @INC, "$FindBin::RealBin/../lib";
}

$ENV{MARKY_CONFIG} = "$FindBin::RealBin/../marky_pub.conf";

# Start command line interface for application
require Mojolicious::Commands;
Mojolicious::Commands->start_app('Marky');
